# Generated by Django 5.0.3 on 2024-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonials",
            options={"verbose_name_plural": "Testimonials"},
        ),
        migrations.AddField(
            model_name="testimonials",
            name="ip",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
