# Generated by Django 5.0.3 on 2024-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_rename_ordreproduct_orderproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="total_price",
            field=models.FloatField(null=True),
        ),
    ]
