# Generated by Django 5.0.3 on 2024-05-18 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_orderproduct_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="total_price",
            new_name="total_amount",
        ),
    ]
